### ISSUE TITLE
Hodnoceni tematu - chyba v prekladu

### ISSUE THREAD

**Issue by Eldenroot** [Eldenroot/MyBB_CZE-translation-1.8.x#64]
Pokud chces hodnotit vlastni tema, tak ho hodi hlasku

"undefined Nemuzete hodnotit vlastni tema"... v angličtině tam to undefined není...

@BKPepe

**Comment by BKPepe** [comment]
Podívám se na to.

**Comment by Eldenroot** [comment]
@BKPepe - stále aktuální...

**Comment by BKPepe** [comment]
During this week, I should have a little bit a free time to look at it.

**Comment by Eldenroot** [comment]
OK, great, thx!

**Comment by BKPepe** [comment]
Regarding this issue, I need to know how to be able to reproduce. Right now, while looking into source code, I am not able to find what could be happening, while comparing translation in the Czech language

https://github.com/Eldenroot/MyBB_CZE-translation-1.8.x/blob/master/czech/ratethread.lang.php

English language:
https://github.com/mybb/mybb/blob/feature/inc/languages/english/ratethread.lang.php

Couldn't it be caused by some plugins, which you are using? What I could do is set up a test instance and try to reproduce it in "real" environment.

**Comment by Eldenroot** [comment]
Bohužel to dělá jen v českém překladu... buď máme někde chybku nebo nevím... angličtina či jiné jazyky testované jsou OK...

**Comment by BKPepe** [comment]
Freshly installed MyBB 1.8.2.4 on my test instance and uploaded, configured the Czech language. It seems I am not able to reproduce it.
![obrazek](https://user-images.githubusercontent.com/4096468/99185090-da167c00-2747-11eb-8f37-085b9666a036.png)

Feel free to provide me steps on how to reproduce. I noticed that the text in the red border is not visible too much.
Going to a little bit tweak it and send PR to MyBB.
